log_format clientlog
    '$remote_addr - [$time_local] '
    '"$request" $status '
    'client_log="$http_x_client_log"';

server {
    listen ${PORT};
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    access_log /dev/stdout;
    error_log /dev/stderr warn;

    location = /log {
        access_log /dev/stdout clientlog;
        error_log /dev/stderr;
        return 204;
    }  

    location /api/ {
        proxy_pass ${CLOUDURL};
        proxy_http_version 1.1;
        proxy_connect_timeout 10s;
        proxy_read_timeout 30s;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        ${PROXY_SSL_SERVER_NAME}
    }

    location = /ping {
        access_log /dev/stdout;
        default_type text/plain;
        return 200 pong;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

}
