services:
  server:
    build: 
      context: .
      dockerfile: server/dockerfile
    expose:
      - "8080"
    networks:
      internal:
        ipv4_address: 172.20.0.10

  client:
    build:
      context: .
      dockerfile: client/dockerfile
    ports:
      - "81:80"
    environment:
      - PORT=80
      - CLOUDURL=http://172.20.0.10:8080
    networks:
      internal:
        ipv4_address: 172.20.0.11

networks:
  internal:
    ipam:
      config:
        - subnet: 172.20.0.0/24
#    internal: true   
