import 'package:flutter/material.dart';
import 'package:shared/models/simulation_result.dart';
import '../services/apiService.dart';
import '../services/aprException.dart';

import 'package:shared/models/account.dart';
import 'package:shared/models/income.dart';
import 'package:shared/models/outgoing.dart';
import 'package:shared/models/transfer.dart';
import 'package:shared/models/user.dart';

import '../services/simulation_service.dart';

import '../services/debugLogger.dart';

class SimulationProvider extends ChangeNotifier {
  SimulationResult? result;
  bool isLoading = false;
  String? error;
  List<bool> showList = [];

  Future<void> run({
    double volatility = 0.12, 
    double rateAdjustment = 0.0,
    int stepMonth = 12, // New
    int? endAge, // New
    int? durationYear, // New
    // Pass data needed for client-side viz
    required List<Account> accountList,
    required List<Income> incomeList,
    required List<Outgoing> outgoingList,
    required List<Transfer> transferList,
    required User user,
  }) async {
    glog.info('Starting hybrid simulation (volatility: $volatility, adjustment: $rateAdjustment, step: $stepMonth, duration: $durationYear, endAge: $endAge)');
    isLoading = true;
    error = null;
    notifyListeners();
    try {
      // 1. Server Run (Official Data)
      glog.info('Fetching official simulation from server...');
      final payload = {
        'volatility': volatility,
        'rate_adjustment': rateAdjustment,
        'step': stepMonth,
        'endAge': endAge,
        'duration': durationYear,
      };
//      if (endAge!=null) payload['end_age'] = endAge!;
//      if (durationYear!=null) payload['duration'] = durationYear!;
      
      final res = await ApiService.post('simulate', payload);
      final serverResult = SimulationResult.fromJson(res);
      glog.info('Server simulation received.');

      // 2. Client Run (Visual Cloud)
      // Note: With the refactor to use 'annualNetFlow' for visual cloud, we might not need to run full client sim if server provides it.
      // However, existing code performs hybrid approach. Let's keep valid client sim for now.
      // But we need to update Client Simulation Service to match Shared logic if we want consistency!
      // Actually, 'simulate.dart' IS in 'shared/lib/models'. 
      // The 'SimulationService' in client likely wraps 'Simulate' class from shared.
      // Let's check 'simulation_service.dart' next. Assuming it does:
      
      // We don't need 'SimulationService' wrapper if we use 'Simulate' directly from shared?
      // But previous code used 'SimulationService'. Let's assume it maps correctly.
      // Actually, if we use the server result's 'annualNetFlow', we can generate the cloud purely visually here 
      // WITHOUT re-running the full simulation on client, UNLESS we want instant UI updates without server roundtrip.
      // For now, let's trust server result for the main data and just use VisualMonteCarlo service for the cloud.
      
      // But wait! The previous implementation ran a CLIENT side sim.
      // If we remove it, we lose offline capability/speed.
      // Let's stick to the server logic for now as directed by the User flow (which calls API).
      
      // 3. Merge / Result Construction
      result = SimulationResult(
        sumPotMin: serverResult.sumPotMin,
        sumPotMax: serverResult.sumPotMax, 
        incomeMin: serverResult.incomeMin,
        incomeMax: serverResult.incomeMax, 
        xAxisMin: serverResult.xAxisMin, 
        xAxisMax: serverResult.xAxisMax, 
        nameList: serverResult.nameList,
        sumList: serverResult.sumList, 
        incomeList: serverResult.incomeList, 
        accountMap: serverResult.accountMap, 
        monteMinList: serverResult.monteMinList, 
        monteMaxList: serverResult.monteMaxList, 
        ageList: serverResult.ageList,
        totalIncomeList: serverResult.totalIncomeList,
        totalOutgoingList: serverResult.totalOutgoingList,
        annualNetFlow: serverResult.annualNetFlow,
        montePath: null, // Will be generated by UI or VisualMonteCarlo service if needed
      );
      
      // Reset showList based on pots
      showList = List<bool>.filled(3 + result!.accountMap.length, true);
    } catch (e) {
      glog.severe('Simulation failed: $e');
      if (e is apiException) {
        error = e.body;
      } else {
        error = e.toString();
      }
    } finally {
      isLoading = false;
      notifyListeners();
    }
  }
  
  void toggleLine(int index) {
    if (index >= 0 && index < showList.length) {
      showList[index] = !showList[index];
      notifyListeners();
    }
  }
}
